# Generated by Django 3.2 on 2021-04-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20210421_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='kodemeli',
            new_name='national_id',
        ),
    ]
