# Generated by Django 3.2 on 2021-04-24 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_rename_kodemeli_member_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='product',
        ),
    ]
