# Generated by Django 3.2 on 2021-04-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20210424_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_check']},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='check',
            new_name='last_check',
        ),
    ]
