# Generated by Django 3.2 on 2021-04-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20210424_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_check',
        ),
        migrations.AddField(
            model_name='member',
            name='access',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red'), ('gray', 'Gray')], default='y', help_text='enter the accesibility status', max_length=10),
        ),
    ]
