# Generated by Django 3.2 on 2021-04-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20210424_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='access',
            field=models.CharField(blank=True, choices=[('a', 'Activate'), ('s', 'Staff status'), ('u', 'Supperuser status')], default='a', help_text='enter the accessibility', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red'), ('gray', 'Gray')], default='y', help_text='enter the accesibility status', max_length=10),
        ),
    ]
