# Generated by Django 3.2 on 2021-04-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_auto_20210424_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(related_name='product', to='goods.Image'),
        ),
    ]
