# Generated by Django 3.2 on 2021-04-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(help_text='enter the image', to='goods.Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
