# Generated by Django 3.2 on 2021-04-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_auto_20210425_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Enter number of your birth', null=True),
        ),
    ]
